### ISSUE TITLE
[BUG] Postgres dependencies are not installed

### ISSUE THREAD

**Issue by foux** [linuxserver/docker-healthchecks#35]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

## Expected Behavior
When configuring a postgres database in local_settings.py, we should be able to use that database.

## Current Behavior
When running `python3 manage.py migrate` to instanciate the database, we get the following error : 
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 20, in <module>
    import psycopg2 as Database
  File "/usr/lib/python3.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: Error loading shared library libpq.so.5: No such file or directory (needed by /usr/lib/python3.7/site-packages/psycopg2/_psycopg.cpython-37m-x86_64-linux-gnu.so)
```

## Steps to Reproduce
1. Install Healthchecks docker image
2. Configure a valid postgres database in /config/local_settings.py
3. Try to instantiate the postgres database by running `python3 manage.py migrate` in `/app/healthchecks`
4.

## Environment
**OS:**  Ubuntu 18.03    
**CPU architecture:** x86_64      
**How docker service was installed:** K8S cluster     

## Proposed fix
Adding `postgresql-dev` to the dockerfile

**Comment by foux** [comment]
Will be fixed by #33
