### ISSUE TITLE
Can't use SMTP server with no username/password

### ISSUE THREAD

**Issue by kaysond** [linuxserver/docker-healthchecks#69]
If I set these env vars:

```
      - DEFAULT_FROM_EMAIL=healthchecks@mail.domain.lan
      - EMAIL_HOST=10.7.1.2
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False
```
and try to use email notifications via an SMTP server that does not require authentication, it fails with this exception:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/app/healthchecks/./hc/lib/emails.py", line 28, in run
    msg.send()
  File "/usr/lib/python3.9/site-packages/django/core/mail/message.py", line 284, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "/usr/lib/python3.9/site-packages/django/core/mail/backends/smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.9/smtplib.py", line 711, in login
    raise SMTPNotSupportedError(
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
```

The issue is in these lines:
https://github.com/linuxserver/docker-healthchecks/blob/ca8ce89655685ae7d7a88242bcedbe2692a8ac96/root/etc/cont-init.d/30-config#L16-L17

which writes `username` and `password` to `local_settings.py` if those env vars aren't set. (I've never seen a `-` parameter expansion so I think it's a typo'd `:-`? ).This is different from default `healthchecks` behavior which defaults to empty strings.

I think a workaround is to set the env vars as empty strings, but I'll also submit a PR to change the defaults to empty strings so it matches upstream behavior.

**Comment by kaysond** [comment]
Not stale see #73
